### ISSUE TITLE
NeoForge 1.20.2 Holder does not implement Supplier, resulting in FluidStack crash.

### ISSUE THREAD

**Issue by brandon3055** [architectury/architectury#484]
In NeoForge 20.2.59-beta `Supplier` was removed from `net.minecraft.core.Holder`

Commit: https://github.com/neoforged/NeoForge/pull/257/commits/ed1b47716277689ddaa4d0743b8cf81011922eb3

This is the patch that was removed:
https://github.com/neoforged/NeoForge/blob/1ba480f54685088db109e719081d23fb5bc3848e/patches/net/minecraft/core/Holder.java.patch

As a result, FluidStack creation via `FluidStack#create(FluidStack, long)` crashes with:
`java.lang.IncompatibleClassChangeError: Class net.minecraft.core.Holder$Reference does not implement the requested interface java.util.function.Supplier`
Full Crash: https://ss.brandon3055.com/ebe85

**Comment by Jab125** [comment]
wasn't that fixed in https://github.com/architectury/architectury-api/pull/483?

**Comment by brandon3055** [comment]
> wasn't that fixed in #483?

That fix appears to be for 1.20.4, It's still broken in 1.20.2

**Comment by shedaniel** [comment]
Should be closed by #485
